### ISSUE TITLE
[Feature Request] Add internal DoH server and ECH (Encrypted ClientHello) support

### ISSUE THREAD

**Issue by 451bttw** [macronut/phantomsocks#49]
1.Chromium最近也添加了ECH功能，但使用ECH需要打开DoH。
2.国外部分DoH目前也会被墙，但用此保护DoH后对于其他的网站就没有保护效果。

**Comment by macronut** [comment]
bdf1bf364769723add607daf49a00d6a236881eb

**Comment by 451bttw** [comment]
Can I set a default DoH server to resolve domains without rules set? I want to avoid DNS pollution as much as possible.

**Comment by macronut** [comment]
default is for all other domains

**Comment by XIU2** [comment]
@macronut 

The SNIProxy protocol is unavailable, I tested every commit and the problem only appeared since "[Portmapping as service](https://github.com/macronut/phantomsocks/commit/2c2776d6527169869a63cbedc55140d9e6338b5d)".

For the same domain name, the handshake will fail when accessed through the SNIProxy protocol, but it is normal to access through the SOCKS protocol.
